language: generic
dist: trusty
os: linux

cache:
  directories:
    - $HOME/.ccache

jobs:
  include:
    - stage: test
      script: if [[ $TRAVIS_PULL_REQUEST != 'false' ]]; then ./.check_changelog.sh; fi
