#
# Copyright (c) 2018 Pilz GmbH & Co. KG
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# names of the drives for which the brake test has to be executed. If empty, the brake test is executed for all drives.
string[] names

---
# error_code is SUCCESS if and only if all brake tests have been successful.
# In case of ROBOT_MOTION_DETECTED no brake test was executed.
int32 error_code
int32 SUCCESS = 0
int32 FAILURE = -1
int32 ROBOT_MOTION_DETECTED = -2
int32 BRAKE_TEST_DURATION_TIMEOUT = -3

# the status array contains detailed reports of the brake test for each drive
BrakeTestStatus[] status

---
